#pragma config(Sensor, in1,    LightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  button,         sensorTouch)
#pragma config(Sensor, dgtl2,  extraButton,    sensorTouch)
#pragma config(Sensor, dgtl3,  sonic,          sensorSONAR_cm)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title:
Team Members:
Date:
Section:


Task Description:


Pseudocode:

var declared at the start for push button

while(ultrasonic sensor is reading more than 15cm)
move forward
when the ultrasonic sensor reads less than 15
move left wheel forward and right backward
wait 1 second
move forward
repeat

flashlight
if lightsenor reads less than x
then start light
else
stop light
loop that


always (while)
sentinal
when push button pressed change var to one and break code


*/


void moveForward(int speed){
	startMotor(rightMotor, speed);
	startMotor(leftMotor, speed);
}

void turnRight(int speed){
	stopMotor(rightMotor);
	stopMotor(leftMotor);
	wait(3);
	motor[leftMotor] = speed;
	motor[rightMotor] = -speed;
	wait(2);
	stopMotor(rightMotor);
	stopMotor(leftMotor);
}



task main(){
	int speed = 50;

	while(1){
		if( SensorValue[sonic] > 15){
			moveForward(speed);
			} else {
			turnRight(speed);
			wait(1);
			moveForward(speed);
		}



	}
}
