#pragma config(Sensor, in1,    LightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  startB,         sensorTouch)
#pragma config(Sensor, dgtl2,  stopB,          sensorTouch)
#pragma config(Sensor, dgtl3,  sonic,          sensorSONAR_cm)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title:
Team Members:
Date:
Section:


Task Description:


Pseudocode:

var declared at the start for push button

while(ultrasonic sensor is reading more than 15cm)
move forward
when the ultrasonic sensor reads less than 15
move left wheel forward and right backward
wait 1 second
move forward
repeat

flashlight
if lightsenor reads less than x
then start light
else
stop light
loop that


always (while)
sentinal
when push button pressed change var to one and break code


*/

task main(){                                     //Program begins, insert code within curly braces
	int stopButtton = 1;
	int startButton = 0;
	while(1){
		if(SensorValue(startB) == 1){
			startButtton = 1;
		}

		if(startButtton && stopButton){
			//main

			if( SensorValue[sonic] < 15){
				turnRight();
				} else {
				moveForward();
			}
		}
	}//big main if

	if(SensorValue(stopB) == 1){
		stopButton = 0;
	}
}


void moveForward(){
	while(SensorValue[sonic] > 15){
		startMotor(rightMotor, 100);
		startMotor(leftMotor, 100);
	}
}

void turnRight(){
	stopMotor(rightMotor);
	stopMotor(leftMotor);
	wait(1);
	motor[portr] = 100;
	motor[portl] = -100;
	wait(3);
}
